### ISSUE TITLE
  SyntaxError: invalid syntax File "humble.py", line 137   with  open(analysis_h_file, 'a+', encoding='utf8') as a_history

### ISSUE THREAD

**Issue by Azathothas** [rfc-st/humble#4]
![image](https://user-images.githubusercontent.com/58171889/231979448-aaea7c18-c521-4b65-9bf2-5297485c76ed.png)
Fixed with on line 137:
![image](https://user-images.githubusercontent.com/58171889/231980140-b7c67a3c-aa5c-4c93-aed7-75b873cd78f1.png)
```python
- with (open(analysis_h_file, 'a+', encoding='utf8') as a_history,
-       open(analysis_h_file, 'r', encoding='utf8') as c_history):
+ with open(analysis_h_file, 'a+', encoding='utf8') as a_history, \
+       open(analysis_h_file, 'r', encoding='utf8') as c_history:
```
![image](https://user-images.githubusercontent.com/58171889/231980608-681496d2-ec57-4f48-87ed-fb3b58e59a73.png)

**Comment by rfc-st** [comment]
I have not been able to reproduce it (in Python 3.11.2 on Linux and Windows). However, I have changed the code based on your suggestion.

Thanks for reporting this error!.
